
package vistas;

/**
 *
 * @author Juan José Cánovas Bustamante
 * @author Rafael Iván Linares Molina
 */
public class VistaHitos extends javax.swing.JFrame {

    /**
     * Creates new form VistaHitos
     */
    public VistaHitos() {
        initComponents();
        setTitle("Listado de Reuniones");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonVolver = new javax.swing.JButton();
        jPanelHitos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableHitos = new javax.swing.JTable();
        jButtonEliminarHito = new javax.swing.JButton();
        jLabelNombreProyecto = new javax.swing.JLabel();
        jLabelNombreProyectoAMostrar = new javax.swing.JLabel();
        jToggleButtonDesbloquearHito = new javax.swing.JToggleButton();
        jPanelFormularioHitos = new javax.swing.JPanel();
        jLabelNombreHito = new javax.swing.JLabel();
        jLabelFechaReunion = new javax.swing.JLabel();
        jLabelUrgente = new javax.swing.JLabel();
        jRadioButtonSi = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jTextFieldNombreHito = new javax.swing.JTextField();
        jButtonAñadirHito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneDescripcion = new javax.swing.JEditorPane();
        jFormattedTextFieldFechaReunion = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        jButtonVolver.setToolTipText("Volver atrás");

        jPanelHitos.setBorder(javax.swing.BorderFactory.createTitledBorder("Hitos del proyecto"));

        jTableHitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha Reunión", "Urgente", "Descripción"
            }
        ));
        jScrollPane2.setViewportView(jTableHitos);

        jButtonEliminarHito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        jButtonEliminarHito.setToolTipText("Eliminar hito");

        jLabelNombreProyecto.setText("Proyecto:");

        jLabelNombreProyectoAMostrar.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabelNombreProyectoAMostrar.setText("Nombre del proyecto");

        jToggleButtonDesbloquearHito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lock yellow.png"))); // NOI18N
        jToggleButtonDesbloquearHito.setToolTipText("Desbloquear hito para su edición");

        javax.swing.GroupLayout jPanelHitosLayout = new javax.swing.GroupLayout(jPanelHitos);
        jPanelHitos.setLayout(jPanelHitosLayout);
        jPanelHitosLayout.setHorizontalGroup(
            jPanelHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHitosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHitosLayout.createSequentialGroup()
                        .addGroup(jPanelHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelHitosLayout.createSequentialGroup()
                                .addComponent(jLabelNombreProyecto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNombreProyectoAMostrar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelHitosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButtonDesbloquearHito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarHito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanelHitosLayout.setVerticalGroup(
            jPanelHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHitosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreProyecto)
                    .addComponent(jLabelNombreProyectoAMostrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEliminarHito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonDesbloquearHito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFormularioHitos.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulario de hitos"));

        jLabelNombreHito.setText("Nombre:");

        jLabelFechaReunion.setText("Fecha de la reunión:");

        jLabelUrgente.setText("¿Urgente?");

        buttonGroup1.add(jRadioButtonSi);
        jRadioButtonSi.setText("Sí");

        buttonGroup1.add(jRadioButtonNo);
        jRadioButtonNo.setText("No");

        jButtonAñadirHito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir.png"))); // NOI18N
        jButtonAñadirHito.setToolTipText("Añadir hito");

        jEditorPaneDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        jScrollPane1.setViewportView(jEditorPaneDescripcion);

        jFormattedTextFieldFechaReunion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));

        javax.swing.GroupLayout jPanelFormularioHitosLayout = new javax.swing.GroupLayout(jPanelFormularioHitos);
        jPanelFormularioHitos.setLayout(jPanelFormularioHitosLayout);
        jPanelFormularioHitosLayout.setHorizontalGroup(
            jPanelFormularioHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioHitosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormularioHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormularioHitosLayout.createSequentialGroup()
                        .addGroup(jPanelFormularioHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFormularioHitosLayout.createSequentialGroup()
                                .addComponent(jLabelFechaReunion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldFechaReunion))
                            .addGroup(jPanelFormularioHitosLayout.createSequentialGroup()
                                .addComponent(jLabelNombreHito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombreHito, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUrgente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonNo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFormularioHitosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAñadirHito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanelFormularioHitosLayout.setVerticalGroup(
            jPanelFormularioHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioHitosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelFormularioHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreHito)
                    .addComponent(jTextFieldNombreHito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormularioHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaReunion)
                    .addComponent(jLabelUrgente)
                    .addComponent(jRadioButtonSi)
                    .addComponent(jRadioButtonNo)
                    .addComponent(jFormattedTextFieldFechaReunion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelFormularioHitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormularioHitosLayout.createSequentialGroup()
                        .addComponent(jButtonAñadirHito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelFormularioHitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelHitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelFormularioHitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaHitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaHitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaHitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaHitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaHitos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAñadirHito;
    private javax.swing.JButton jButtonEliminarHito;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JEditorPane jEditorPaneDescripcion;
    private javax.swing.JFormattedTextField jFormattedTextFieldFechaReunion;
    private javax.swing.JLabel jLabelFechaReunion;
    private javax.swing.JLabel jLabelNombreHito;
    private javax.swing.JLabel jLabelNombreProyecto;
    private javax.swing.JLabel jLabelNombreProyectoAMostrar;
    private javax.swing.JLabel jLabelUrgente;
    private javax.swing.JPanel jPanelFormularioHitos;
    private javax.swing.JPanel jPanelHitos;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonSi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableHitos;
    private javax.swing.JTextField jTextFieldNombreHito;
    private javax.swing.JToggleButton jToggleButtonDesbloquearHito;
    // End of variables declaration//GEN-END:variables
}
