/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author Khanox
 */
public class VistaPersonal extends javax.swing.JFrame {

    /**
     * Creates new form Personal
     */
    public VistaPersonal() {
        initComponents();
        
        setTitle("Datos Personales");
        setLocationRelativeTo(null);
        setResizable(false); 
        
        jButtonVolver.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                VistaProyectos obj = new VistaProyectos();
                obj.setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGestionPersonal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGestionPersonal = new javax.swing.JTable();
        jPanelFormularioDeAlta = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido1 = new javax.swing.JLabel();
        jLabelApellido2 = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelDNI = new javax.swing.JLabel();
        jLabelNSS = new javax.swing.JLabel();
        jLabelTitulacion = new javax.swing.JLabel();
        jLabelFechaAltaSistema = new javax.swing.JLabel();
        jTextFieldNSS = new javax.swing.JTextField();
        jTextFieldTitulacion = new javax.swing.JTextField();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jLabelHorasJornadaDiaria = new javax.swing.JLabel();
        jButtonAñadirRegistro = new javax.swing.JButton();
        jTextFieldDNI = new javax.swing.JTextField();
        jFormattedTextFieldFechaNac = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFechaAltaSis = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHorasJornadaDiaria = new javax.swing.JFormattedTextField();
        jButtonEliminarRegistro = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jToggleButtonModificarRegistro = new javax.swing.JToggleButton();
        jComboBoxMostrarPersonal = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGestionPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión de personal"));

        jTableGestionPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableGestionPersonal);

        jPanelFormularioDeAlta.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulario de personal"));

        jLabelNombre.setText("Nombre:");

        jLabelApellido1.setText("Apellido1:");

        jLabelApellido2.setText("Apellido2:");

        jLabelTelefono.setText("Teléfono:");

        jLabelEmail.setText("E-mail:");

        jLabelDNI.setText("DNI:");

        jLabelNSS.setText("NSS:");

        jLabelTitulacion.setText("Titulación:");

        jLabelFechaAltaSistema.setText("Fecha alta sistema:");

        jLabelFechaNacimiento.setText("Fecha Nacimiento:");

        jLabelHorasJornadaDiaria.setText("Horas jornada diaria:");

        jButtonAñadirRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        jButtonAñadirRegistro.setToolTipText("Añadir registro");

        jFormattedTextFieldFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));

        jFormattedTextFieldFechaAltaSis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));

        jFormattedTextFieldHorasJornadaDiaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        javax.swing.GroupLayout jPanelFormularioDeAltaLayout = new javax.swing.GroupLayout(jPanelFormularioDeAlta);
        jPanelFormularioDeAlta.setLayout(jPanelFormularioDeAltaLayout);
        jPanelFormularioDeAltaLayout.setHorizontalGroup(
            jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioDeAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFormularioDeAltaLayout.createSequentialGroup()
                        .addComponent(jLabelTitulacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTitulacion))
                    .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelFormularioDeAltaLayout.createSequentialGroup()
                            .addComponent(jLabelFechaNacimiento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextFieldFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelFormularioDeAltaLayout.createSequentialGroup()
                            .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelDNI)
                                .addComponent(jLabelNombre))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(jTextFieldNombre)))))
                .addGap(12, 12, 12)
                .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFormularioDeAltaLayout.createSequentialGroup()
                        .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelApellido1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelNSS, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabelTelefono, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNSS, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFormularioDeAltaLayout.createSequentialGroup()
                        .addComponent(jLabelHorasJornadaDiaria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldHorasJornadaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFormularioDeAltaLayout.createSequentialGroup()
                        .addComponent(jLabelFechaAltaSistema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldFechaAltaSis, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormularioDeAltaLayout.createSequentialGroup()
                        .addComponent(jLabelApellido2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormularioDeAltaLayout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAñadirRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelFormularioDeAltaLayout.setVerticalGroup(
            jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioDeAltaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAñadirRegistro)
                    .addGroup(jPanelFormularioDeAltaLayout.createSequentialGroup()
                        .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDNI)
                            .addComponent(jTextFieldNSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNSS)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFechaAltaSistema)
                            .addComponent(jFormattedTextFieldFechaAltaSis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelApellido1)
                                .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelApellido2)
                                .addComponent(jTextFieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmail)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefono)
                            .addComponent(jLabelFechaNacimiento)
                            .addComponent(jFormattedTextFieldFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormularioDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulacion)
                    .addComponent(jLabelHorasJornadaDiaria)
                    .addComponent(jFormattedTextFieldHorasJornadaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jButtonEliminarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete.png"))); // NOI18N
        jButtonEliminarRegistro.setToolTipText("Eliminar registro");

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        jButtonVolver.setToolTipText("Volver atrás");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jToggleButtonModificarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lock yellow.png"))); // NOI18N
        jToggleButtonModificarRegistro.setToolTipText("Desbloquear fila para edición");

        jComboBoxMostrarPersonal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mostrar todos", "Mostrar sólo jefes de proyecto", "Mostrar sólo desarrolladores" }));

        javax.swing.GroupLayout jPanelGestionPersonalLayout = new javax.swing.GroupLayout(jPanelGestionPersonal);
        jPanelGestionPersonal.setLayout(jPanelGestionPersonalLayout);
        jPanelGestionPersonalLayout.setHorizontalGroup(
            jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGestionPersonalLayout.createSequentialGroup()
                        .addGroup(jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGestionPersonalLayout.createSequentialGroup()
                                .addGap(0, 756, Short.MAX_VALUE)
                                .addComponent(jToggleButtonModificarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(jPanelGestionPersonalLayout.createSequentialGroup()
                                .addComponent(jComboBoxMostrarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanelGestionPersonalLayout.createSequentialGroup()
                        .addComponent(jPanelFormularioDeAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanelGestionPersonalLayout.setVerticalGroup(
            jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonModificarRegistro)
                    .addComponent(jButtonEliminarRegistro)
                    .addComponent(jComboBoxMostrarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGestionPersonalLayout.createSequentialGroup()
                        .addComponent(jPanelFormularioDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGestionPersonalLayout.createSequentialGroup()
                        .addComponent(jButtonVolver)
                        .addGap(66, 66, 66))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelGestionPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelGestionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        VistaProyectos obj = new VistaProyectos();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadirRegistro;
    private javax.swing.JButton jButtonEliminarRegistro;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox jComboBoxMostrarPersonal;
    private javax.swing.JFormattedTextField jFormattedTextFieldFechaAltaSis;
    private javax.swing.JFormattedTextField jFormattedTextFieldFechaNac;
    private javax.swing.JFormattedTextField jFormattedTextFieldHorasJornadaDiaria;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFechaAltaSistema;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelHorasJornadaDiaria;
    private javax.swing.JLabel jLabelNSS;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTitulacion;
    private javax.swing.JPanel jPanelFormularioDeAlta;
    private javax.swing.JPanel jPanelGestionPersonal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGestionPersonal;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNSS;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldTitulacion;
    private javax.swing.JToggleButton jToggleButtonModificarRegistro;
    // End of variables declaration//GEN-END:variables
}
