/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import modelos.ModelosEntidades.ModeloVistaProyectos;
import modelos.SesionActual;

/**
 *
 * @author Khanox
 */
public class VistaProyectos extends javax.swing.JFrame {

    /**
     * Creates new form Proyectos
     */
    public VistaProyectos() {
        initComponents();
        setTitle("Proyectos");
        setLocationRelativeTo(null);
        setResizable(false);
        jTableProyectos.setModel(new ModeloVistaProyectos());
        
        jButtonVolver.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent ae) {
                SesionActual.setId_datos(0);
                SesionActual.setId_usuario(0);
                SesionActual.setId_rol_app(0);
                SesionActual.setUsuario("");
                SesionActual.setContraseña("");
                VistaLogin obj = new VistaLogin();
                obj.setVisible(true);
                dispose();
            }
        });
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaProyectos().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProyectos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProyectos = new javax.swing.JTable();
        jPanelOpcionesProyecto = new javax.swing.JPanel();
        jButtonCrearProyecto = new javax.swing.JButton();
        jButtonEliminarProyecto = new javax.swing.JButton();
        jButtonVerProyecto = new javax.swing.JButton();
        jButtonVerHitosProyecto = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jPanelOpcionesPersonal = new javax.swing.JPanel();
        jButtonGestionPersonal = new javax.swing.JButton();
        jButtonGestionCuentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelProyectos.setBorder(javax.swing.BorderFactory.createTitledBorder("Proyectos"));

        jTableProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre del proyecto", "Jefe de proyecto", "Fecha de inicio", "Fecha de finalización estimada", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProyectos);

        jPanelOpcionesProyecto.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de proyecto"));

        jButtonCrearProyecto.setText("Crear un proyecto");
        jButtonCrearProyecto.setMaximumSize(new java.awt.Dimension(105, 50));
        jButtonCrearProyecto.setMinimumSize(new java.awt.Dimension(105, 50));
        jButtonCrearProyecto.setPreferredSize(new java.awt.Dimension(105, 50));

        jButtonEliminarProyecto.setText("Eliminar un proyecto");
        jButtonEliminarProyecto.setMaximumSize(new java.awt.Dimension(105, 50));
        jButtonEliminarProyecto.setMinimumSize(new java.awt.Dimension(105, 50));
        jButtonEliminarProyecto.setPreferredSize(new java.awt.Dimension(105, 50));

        jButtonVerProyecto.setText("Ver proyecto en detalle");

        jButtonVerHitosProyecto.setText("Ver hitos de un proyecto");
        jButtonVerHitosProyecto.setMaximumSize(new java.awt.Dimension(105, 50));
        jButtonVerHitosProyecto.setMinimumSize(new java.awt.Dimension(105, 50));
        jButtonVerHitosProyecto.setPreferredSize(new java.awt.Dimension(105, 50));

        javax.swing.GroupLayout jPanelOpcionesProyectoLayout = new javax.swing.GroupLayout(jPanelOpcionesProyecto);
        jPanelOpcionesProyecto.setLayout(jPanelOpcionesProyectoLayout);
        jPanelOpcionesProyectoLayout.setHorizontalGroup(
            jPanelOpcionesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesProyectoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelOpcionesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcionesProyectoLayout.createSequentialGroup()
                        .addComponent(jButtonVerProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVerHitosProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOpcionesProyectoLayout.createSequentialGroup()
                        .addComponent(jButtonCrearProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanelOpcionesProyectoLayout.setVerticalGroup(
            jPanelOpcionesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOpcionesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVerHitosProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        jButtonVolver.setToolTipText("Volver atrás");

        jPanelOpcionesPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de personal"));

        jButtonGestionPersonal.setText("Gestión de personal");

        jButtonGestionCuentas.setText("Gestión de cuentas de usuario");

        javax.swing.GroupLayout jPanelOpcionesPersonalLayout = new javax.swing.GroupLayout(jPanelOpcionesPersonal);
        jPanelOpcionesPersonal.setLayout(jPanelOpcionesPersonalLayout);
        jPanelOpcionesPersonalLayout.setHorizontalGroup(
            jPanelOpcionesPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGestionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGestionCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanelOpcionesPersonalLayout.setVerticalGroup(
            jPanelOpcionesPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGestionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGestionCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanelProyectosLayout = new javax.swing.GroupLayout(jPanelProyectos);
        jPanelProyectos.setLayout(jPanelProyectosLayout);
        jPanelProyectosLayout.setHorizontalGroup(
            jPanelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProyectosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelOpcionesProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
            .addGroup(jPanelProyectosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelOpcionesPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProyectosLayout.setVerticalGroup(
            jPanelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProyectosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelOpcionesProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOpcionesPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearProyecto;
    private javax.swing.JButton jButtonEliminarProyecto;
    private javax.swing.JButton jButtonGestionCuentas;
    private javax.swing.JButton jButtonGestionPersonal;
    private javax.swing.JButton jButtonVerHitosProyecto;
    private javax.swing.JButton jButtonVerProyecto;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JPanel jPanelOpcionesPersonal;
    private javax.swing.JPanel jPanelOpcionesProyecto;
    private javax.swing.JPanel jPanelProyectos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProyectos;
    // End of variables declaration//GEN-END:variables
}
