/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import modelos.ModelosEntidades.ModeloVistaProyectos;
import modelos.SesionActual;

/**
 *
 * @author Khanox
 */
public class VistaProyectos extends javax.swing.JFrame {

    /**
     * Creates new form Proyectos
     */
    public VistaProyectos() {
        initComponents();
        setTitle("Proyectos");
        setLocationRelativeTo(null);
        setResizable(false); 
        
        if (SesionActual.getId_rol_app() != 1) {
            jButtonCrearProyecto.setEnabled(false);
            jButtonEliminarProyecto.setEnabled(false);
            jButtonGestionCuentas.setEnabled(false);
            jButtonGestionPersonal.setEnabled(false);
            
        }

        jTableProyectos.setModel(new ModeloVistaProyectos());

        jButtonVolver.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                SesionActual.setId_datos(0);
                SesionActual.setId_usuario(0);
                SesionActual.setId_rol_app(0);
                SesionActual.setUsuario("");
                SesionActual.setContraseña("");
                VistaLogin obj = new VistaLogin();
                obj.setVisible(true);
                dispose();
            }
        });
        
        jButtonCrearProyecto.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                VistaProyectoEnDetalle obj = new VistaProyectoEnDetalle();
                obj.setVisible(true);
                dispose();
            }
        });
        
        jButtonGestionCuentas.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                VistaListaUsuarios obj = new VistaListaUsuarios();
                obj.setVisible(true);
                dispose();
            }
        });
        
        jButtonGestionPersonal.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                VistaPersonal obj = new VistaPersonal();
                obj.setVisible(true);
                dispose();
            }
        });
        
        jButtonVerHitosProyecto.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                VistaHitos obj = new VistaHitos();
                obj.setVisible(true);
                dispose();
            }
        });
        
    }

 

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProyectos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProyectos = new javax.swing.JTable();
        jPanelOpcionesProyecto = new javax.swing.JPanel();
        jButtonCrearProyecto = new javax.swing.JButton();
        jButtonEliminarProyecto = new javax.swing.JButton();
        jButtonVerProyecto = new javax.swing.JButton();
        jButtonVerHitosProyecto = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jPanelOpcionesPersonal = new javax.swing.JPanel();
        jButtonGestionPersonal = new javax.swing.JButton();
        jButtonGestionCuentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelProyectos.setBorder(javax.swing.BorderFactory.createTitledBorder("Proyectos"));

        jTableProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre del proyecto", "Jefe de proyecto", "Fecha de inicio", "Fecha de finalización estimada", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProyectos);

        jPanelOpcionesProyecto.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de proyecto"));

        jButtonCrearProyecto.setText("Crear un proyecto");
        jButtonCrearProyecto.setMaximumSize(new java.awt.Dimension(105, 50));
        jButtonCrearProyecto.setMinimumSize(new java.awt.Dimension(105, 50));
        jButtonCrearProyecto.setPreferredSize(new java.awt.Dimension(105, 50));

        jButtonEliminarProyecto.setText("Eliminar un proyecto");
        jButtonEliminarProyecto.setMaximumSize(new java.awt.Dimension(105, 50));
        jButtonEliminarProyecto.setMinimumSize(new java.awt.Dimension(105, 50));
        jButtonEliminarProyecto.setPreferredSize(new java.awt.Dimension(105, 50));

        jButtonVerProyecto.setText("Ver proyecto en detalle");

        jButtonVerHitosProyecto.setText("Ver hitos de un proyecto");
        jButtonVerHitosProyecto.setMaximumSize(new java.awt.Dimension(105, 50));
        jButtonVerHitosProyecto.setMinimumSize(new java.awt.Dimension(105, 50));
        jButtonVerHitosProyecto.setPreferredSize(new java.awt.Dimension(105, 50));

        javax.swing.GroupLayout jPanelOpcionesProyectoLayout = new javax.swing.GroupLayout(jPanelOpcionesProyecto);
        jPanelOpcionesProyecto.setLayout(jPanelOpcionesProyectoLayout);
        jPanelOpcionesProyectoLayout.setHorizontalGroup(
            jPanelOpcionesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesProyectoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelOpcionesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcionesProyectoLayout.createSequentialGroup()
                        .addComponent(jButtonVerProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVerHitosProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOpcionesProyectoLayout.createSequentialGroup()
                        .addComponent(jButtonCrearProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanelOpcionesProyectoLayout.setVerticalGroup(
            jPanelOpcionesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesProyectoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelOpcionesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOpcionesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVerHitosProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Exit.png"))); // NOI18N
        jButtonVolver.setToolTipText("Cerrar sesión");

        jPanelOpcionesPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de personal"));

        jButtonGestionPersonal.setText("Gestión de personal");

        jButtonGestionCuentas.setText("Gestión de cuentas de usuario");

        javax.swing.GroupLayout jPanelOpcionesPersonalLayout = new javax.swing.GroupLayout(jPanelOpcionesPersonal);
        jPanelOpcionesPersonal.setLayout(jPanelOpcionesPersonalLayout);
        jPanelOpcionesPersonalLayout.setHorizontalGroup(
            jPanelOpcionesPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesPersonalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelOpcionesPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGestionCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGestionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanelOpcionesPersonalLayout.setVerticalGroup(
            jPanelOpcionesPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesPersonalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButtonGestionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGestionCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanelProyectosLayout = new javax.swing.GroupLayout(jPanelProyectos);
        jPanelProyectos.setLayout(jPanelProyectosLayout);
        jPanelProyectosLayout.setHorizontalGroup(
            jPanelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProyectosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelProyectosLayout.createSequentialGroup()
                        .addComponent(jPanelOpcionesProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelOpcionesPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProyectosLayout.setVerticalGroup(
            jPanelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProyectosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProyectosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelOpcionesPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelOpcionesProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelProyectosLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButtonVolver)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearProyecto;
    private javax.swing.JButton jButtonEliminarProyecto;
    private javax.swing.JButton jButtonGestionCuentas;
    private javax.swing.JButton jButtonGestionPersonal;
    private javax.swing.JButton jButtonVerHitosProyecto;
    private javax.swing.JButton jButtonVerProyecto;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JPanel jPanelOpcionesPersonal;
    private javax.swing.JPanel jPanelOpcionesProyecto;
    private javax.swing.JPanel jPanelProyectos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProyectos;
    // End of variables declaration//GEN-END:variables
}
