/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Khanox
 */
public class VistaTareasEnDetalle extends javax.swing.JFrame {

    /**
     * Creates new form FormularioTareasSubtareas
     */
    public VistaTareasEnDetalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelFormularioTareas = new javax.swing.JPanel();
        jRadioButtonSubtarea = new javax.swing.JRadioButton();
        jRadioButtonTarea = new javax.swing.JRadioButton();
        jLabelTareaSubtarea = new javax.swing.JLabel();
        jLabelNombreTarea = new javax.swing.JLabel();
        jLabelFechaInicio = new javax.swing.JLabel();
        jTextFieldNombreTarea = new javax.swing.JTextField();
        jLabelDuracionEstimada = new javax.swing.JLabel();
        jTextFieldDuracionEstimada = new javax.swing.JTextField();
        jLabelDias = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jFormattedTextFieldFechaInicio = new javax.swing.JFormattedTextField();
        jPanelDesarrolladoresAsignados = new javax.swing.JPanel();
        jLabelDesarrolladores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDesarrolladores = new javax.swing.JTable();
        jComboBoxDesarrolladores = new javax.swing.JComboBox();
        jButtonAsignarATarea = new javax.swing.JButton();
        jButtonEliminarDeTarea = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonCrearTarea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFormularioTareas.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de la tarea / subtarea"));

        buttonGroup1.add(jRadioButtonSubtarea);
        jRadioButtonSubtarea.setText("Subtarea");

        buttonGroup1.add(jRadioButtonTarea);
        jRadioButtonTarea.setText("Tarea");

        jLabelTareaSubtarea.setText("¿Tarea o subtarea?");

        jLabelNombreTarea.setText("Nombre:");

        jLabelFechaInicio.setText("Fecha de inicio:");

        jLabelDuracionEstimada.setText("Duración estimada:");

        jLabelDias.setText("días");

        jLabelEstado.setText("Estado:");

        jFormattedTextFieldFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));

        javax.swing.GroupLayout jPanelFormularioTareasLayout = new javax.swing.GroupLayout(jPanelFormularioTareas);
        jPanelFormularioTareas.setLayout(jPanelFormularioTareasLayout);
        jPanelFormularioTareasLayout.setHorizontalGroup(
            jPanelFormularioTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormularioTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFormularioTareasLayout.createSequentialGroup()
                        .addComponent(jLabelDuracionEstimada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDuracionEstimada, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDias)
                        .addGap(39, 39, 39)
                        .addComponent(jLabelEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormularioTareasLayout.createSequentialGroup()
                        .addComponent(jLabelNombreTarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombreTarea)))
                .addGap(39, 39, 39)
                .addGroup(jPanelFormularioTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormularioTareasLayout.createSequentialGroup()
                        .addComponent(jLabelTareaSubtarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonTarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonSubtarea))
                    .addGroup(jPanelFormularioTareasLayout.createSequentialGroup()
                        .addComponent(jLabelFechaInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanelFormularioTareasLayout.setVerticalGroup(
            jPanelFormularioTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioTareasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelFormularioTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreTarea)
                    .addComponent(jTextFieldNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaInicio)
                    .addComponent(jFormattedTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormularioTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDuracionEstimada)
                    .addComponent(jTextFieldDuracionEstimada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDias)
                    .addComponent(jLabelEstado)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTareaSubtarea)
                    .addComponent(jRadioButtonTarea)
                    .addComponent(jRadioButtonSubtarea))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDesarrolladoresAsignados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelDesarrolladores.setText("Desarrolladores asignados:");

        jTableDesarrolladores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido1", "Apellido2", "Titulación", "Sueldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDesarrolladores);

        jComboBoxDesarrolladores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apellido1 Apellido2, Nombre" }));

        jButtonAsignarATarea.setText("Asignar a tarea / subtarea");

        jButtonEliminarDeTarea.setText("Eliminar de tarea / subtarea");

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        jButtonVolver.setToolTipText("Volver atrás");

        jButtonCrearTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save-48.png"))); // NOI18N
        jButtonCrearTarea.setToolTipText("Guardar cambios");

        javax.swing.GroupLayout jPanelDesarrolladoresAsignadosLayout = new javax.swing.GroupLayout(jPanelDesarrolladoresAsignados);
        jPanelDesarrolladoresAsignados.setLayout(jPanelDesarrolladoresAsignadosLayout);
        jPanelDesarrolladoresAsignadosLayout.setHorizontalGroup(
            jPanelDesarrolladoresAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDesarrolladoresAsignadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCrearTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(jPanelDesarrolladoresAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDesarrolladoresAsignadosLayout.createSequentialGroup()
                    .addGroup(jPanelDesarrolladoresAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelDesarrolladoresAsignadosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDesarrolladoresAsignadosLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(jPanelDesarrolladoresAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelDesarrolladoresAsignadosLayout.createSequentialGroup()
                                    .addComponent(jComboBoxDesarrolladores, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonAsignarATarea))
                                .addGroup(jPanelDesarrolladoresAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonEliminarDeTarea)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDesarrolladores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        jPanelDesarrolladoresAsignadosLayout.setVerticalGroup(
            jPanelDesarrolladoresAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDesarrolladoresAsignadosLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jButtonCrearTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelDesarrolladoresAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDesarrolladoresAsignadosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelDesarrolladores)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelDesarrolladoresAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxDesarrolladores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAsignarATarea)
                        .addComponent(jButtonEliminarDeTarea))
                    .addGap(18, 18, 18)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelFormularioTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDesarrolladoresAsignados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelFormularioTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDesarrolladoresAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTareasEnDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTareasEnDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTareasEnDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTareasEnDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTareasEnDetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAsignarATarea;
    private javax.swing.JButton jButtonCrearTarea;
    private javax.swing.JButton jButtonEliminarDeTarea;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox jComboBoxDesarrolladores;
    private javax.swing.JFormattedTextField jFormattedTextFieldFechaInicio;
    private javax.swing.JLabel jLabelDesarrolladores;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelDuracionEstimada;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelNombreTarea;
    private javax.swing.JLabel jLabelTareaSubtarea;
    private javax.swing.JPanel jPanelDesarrolladoresAsignados;
    private javax.swing.JPanel jPanelFormularioTareas;
    private javax.swing.JRadioButton jRadioButtonSubtarea;
    private javax.swing.JRadioButton jRadioButtonTarea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDesarrolladores;
    private javax.swing.JTextField jTextFieldDuracionEstimada;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldNombreTarea;
    // End of variables declaration//GEN-END:variables
}
